# enable_experimental_conpty_backend = false
# indexed_colors = []
live_config_reload = true
# "window.dynamic_title" = true
# "window.opacity" = 1.0

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true
# name = "TokyoNight Storm"

# [[colors.indexed_colors]]
# color = "0xff9e64"
# index = 16

# [[colors.indexed_colors]]
# color = "0xdb4b4b"
# index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x1D202F"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x24283b"
foreground = "0xc0caf5"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 14.5

[font.normal]
family = "MesloLGS Nerd Font Mono"

[font.bold]
family = "MesloLGS Nerd Font Mono"

[font.italic]
family = "MesloLGS Nerd Font Mono"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.hints]
# modifiers = "None"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["-u"]
program = "/usr/local/bin/tmux"

[window]
decorations = "buttonless"
dynamic_padding = false
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5
