plugins:
  - prettier-plugin-sql
overrides:
  - files:
      - '*.sql'
    options:
      language: postgresql
      keywordCase: upper
      dataTypeCase: upper
      functionCase: upper
      identifierCase: preserve
      indentStyle: tabularRight
      expressionWidth: 96
